spring:
  application:
    name: airlines
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/airlines
    username: postgres
    password: 2334
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

admin:
  username: ${SPRING.ADMIN.USERNAME}
  password: ${SPRING.ADMIN.PASSWORD}


server:
  servlet:
    context-path: /api/v1/

logging:
  level:
    root: info